# Generated by Django 2.2.12 on 2020-05-26 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSalary',
            fields=[
                ('id', models.CharField(primary_key=True, max_length=24, serialize=False)),
                ('login', models.CharField(max_length=24)),
                ('name', models.CharField(max_length=100)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
