# Generated by Django 2.2.12 on 2020-05-27 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeesalary',
            options={'ordering': ['id', 'name', 'login', 'salary']},
        ),
    ]
